version: 2.1

parameters:
  dir_a:
    type: boolean
    default: false
  dir_b:
    type: boolean
    default: false

jobs:
  job-for-dir_a:
    docker:
      - image: cimg/node:lts
    steps:
      - run:
          name: "NodeのVersionを表示"
          command: |
            echo `node -v` 
  job-for-dir_b:
    docker:
      - image: cimg/node:15.0.1-browsers
    steps:
      - run:
          name: "NodeのVersionを表示"
          command: |
            echo `node -v` 

workflows:
  build-lts:
    when: << pipeline.parameters.dir_a >>
    jobs:
      - job-for-dir_a
  build-v15:
    when: << pipeline.parameters.dir_a >>
    jobs:
      - job-for-dir_b
