version: 2.1

parameters:
  dir_A:
    type: boolean
    default: false
  dir_B:
    type: boolean
    default: false

jobs:
  job-for-dir_A:
    docker:
      - image: cimg/node:lts
    steps:
      - run:
          name: "NodeのVersionを表示"
          command: |
            echo `node -v` 
  job-for-dir_B:
    docker:
      - image: cimg/node:15.0.1-browsers
    steps:
      - run:
          name: "NodeのVersionを表示"
          command: |
            echo `node -v` 

workflows:
  build-dir_A:
    when: << pipeline.parameters.dir_A >>
    jobs:
      - job-for-dir_A
      　　　　context: oidc-aws
  build-dir_B:
    when: << pipeline.parameters.dir_B >>
    jobs:
      - job-for-dir_B
