version: 2.1

jobs:
  node-lts:
    docker:
      - image: cimg/node:lts
    steps:
      - run:
          name: "NodeのVersionを表示"
          command: |
            echo `node -v` 
  node-15:
    docker:
      - image: cimg/node:15.0.1-browsers
    steps:
      - run:
          name: "NodeのVersionを表示"
          command: |
            echo `node -v` 

workflows:
  build-test-deploy:
    jobs:
      - node-lts
      - node-15
